(function(){'use strict';
const $=s=>document.querySelector(s);const shortlist=new Set();
const categoryNames={thermal:'THERMAL & DRYING',food:'FOOD PROCESSING',green:'GREEN ENERGY',metal:'METALLURGICAL',process:'PROCESS EQUIPMENT'};
const applications={thermal:'Discuss your operating temperature, required capacity, fuel source and target moisture or steam requirements.',food:'Tell us about your product, batch size, production target and available fuel source.',green:'Share your feedstock, fuel availability, process heat requirements and operating schedule.',metal:'Discuss your metal, batch weight, operating temperature and heating cycle.',process:'Share your material, working capacity, site layout and handling requirements.'};
function renderShortlist(){document.querySelectorAll('[data-shortlist]').forEach(b=>{const selected=shortlist.has(Number(b.dataset.shortlist));b.setAttribute('aria-pressed',String(selected));b.textContent=selected?'✓':'+';});$('#shortlistBar').hidden=!shortlist.size;$('#shortlistCount').textContent=shortlist.size;document.querySelector('.wa-float').style.bottom=shortlist.size?'90px':'';}
document.addEventListener('click',e=>{const select=e.target.closest('[data-shortlist]');if(select){const id=Number(select.dataset.shortlist);if(shortlist.has(id))shortlist.delete(id);else shortlist.add(id);renderShortlist();}const detail=e.target.closest('[data-details]');if(detail){const p=window.aryanProducts[Number(detail.dataset.details)];$('#machineDetails').replaceChildren();const label=document.createElement('span');label.className='eyebrow';label.textContent=categoryNames[p.cat];const title=document.createElement('h2');title.textContent=p.name;const desc=document.createElement('p');desc.textContent=p.desc;const note=document.createElement('div');note.className='spec-note';const noteTitle=document.createElement('b');noteTitle.textContent='ENGINEERED AROUND YOUR REQUIREMENTS';const noteText=document.createElement('p');noteText.textContent=applications[p.cat]+' Specifications and pricing are confirmed after consultation.';note.append(noteTitle,noteText);const enquire=document.createElement('a');enquire.href='#contact';enquire.className='btn btn--primary';enquire.textContent='Discuss this machine ↗';enquire.onclick=()=>{$('#product').value=p.name;$('#machineDialog').close();};$('#machineDetails').append(label,title,desc,note,enquire);$('#machineDialog').showModal();}});
$('#closeMachine').onclick=()=>$('#machineDialog').close();$('#machineDialog').addEventListener('click',e=>{if(e.target===$('#machineDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#clearShortlist').onclick=()=>{shortlist.clear();renderShortlist();};$('#enquireShortlist').onclick=()=>{const names=[...shortlist].map(i=>window.aryanProducts[i].name);$('#message').value='I would like to discuss these machines:\n'+names.map(n=>'• '+n).join('\n')+'\n\nApplication / capacity: ';$('#product').value=names.length===1?names[0]:'';};
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--reading',max>0?(scrollY/max*100)+'%':'0%');},{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#machineDialog').open){e.preventDefault();$('#machineSearch').focus();}if(e.key==='Escape'){$('#nav').classList.remove('open');$('#navToggle').classList.remove('open');$('#navToggle').setAttribute('aria-expanded','false');}});
$('#navToggle').setAttribute('aria-expanded','false');$('#navToggle').setAttribute('aria-controls','nav');new MutationObserver(()=>{$('#navToggle').setAttribute('aria-expanded',String($('#nav').classList.contains('open')));}).observe($('#nav'),{attributes:true,attributeFilter:['class']});
document.querySelectorAll('.why__icon').forEach((el,i)=>el.textContent='0'+(i+1)+' /');document.querySelectorAll('.industry__ico').forEach((el,i)=>el.textContent=String(i+1).padStart(2,'0'));
const lightbox=$('#lightbox');lightbox.setAttribute('role','dialog');lightbox.setAttribute('aria-modal','true');lightbox.setAttribute('aria-label','Workshop film');let lastFocus=null;new MutationObserver(()=>{if(lightbox.classList.contains('open')){lastFocus=document.activeElement;$('#lightboxClose').focus();}else if(lastFocus){lastFocus.focus();lastFocus=null;}}).observe(lightbox,{attributes:true,attributeFilter:['aria-hidden']});
lightbox.addEventListener('keydown',e=>{if(e.key==='Tab'){const controls=[...lightbox.querySelectorAll('button,video')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
// Pause decorative workshop footage for reduced-motion visitors and when offscreen.
const reduce=matchMedia('(prefers-reduced-motion: reduce)');const aboutVideo=$('.about__media video');if(aboutVideo){aboutVideo.removeAttribute('autoplay');if(reduce.matches)aboutVideo.pause();else new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)aboutVideo.play().catch(()=>{});else aboutVideo.pause();}),{threshold:.1}).observe(aboutVideo);}
const navLinks=[...document.querySelectorAll('.nav>a[href^="#"]')];new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(a=>{if(a.hash==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});});},{rootMargin:'-20% 0px -55% 0px'}).observe($('#products'));
})();
document.addEventListener('DOMContentLoaded',()=>{
const drawings={food:'M20 39L62 17 104 39 62 61ZM20 39v15l42 23 42-23V39M31 61v24m61-24v24M30 33l32 17 31-17M62 17V9m-18 20V15m36 15V15',green:'M27 29L67 9 98 27 58 47ZM27 29v34l31 18 40-20V27M58 47v34M35 40v17l16 9V49ZM67 50l22-12v18L67 69ZM34 69v18m48-16v16M13 56l14-8m-14 8v17l18 10 17-9',metal:'M28 24L61 7 95 24v50L61 91 28 74ZM28 24l33 18 34-18M61 42v49M38 41l14 8v26l-14-8ZM69 50l18-10v27L69 78ZM42 27l18 9 18-9M57 16l4 8 5-8',process:'M27 22C27 5 92 5 92 22v49c0 17-65 17-65 0ZM27 22c0 17 65 17 65 0M27 63c0 17 65 17 65 0M35 80v10m49-10v10M60 9V2m32 48h17v19'};
document.querySelectorAll('.pcard').forEach(card=>{if(drawings[card.dataset.cat])card.querySelector('.machine-icon').innerHTML='<path d="'+drawings[card.dataset.cat]+'"/>';});
});
